#// TODO revisar CI
name: NestJs Workflow

on: [ pull_request ]

jobs:
  ci:
    runs-on: ubuntu-latest

#// TODO remove
#    env:
#      NPM_GITHUB_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Yarn install
        run: yarn install --immutable

      - name: Lint
        run: yarn lint

      - name: Test + Coverage
        run: yarn test:cov

      - name: Lib build
        run: yarn build
